name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2    
    - name: Initialize repository
      run: make init
    - name: Create bundle
      run: make bundle
    - uses: actions/upload-artifact@v2
      with:
        name: vimrc
        path: bundle.tgz

